server:
  # 服务端口号
  port: 8073
spring:
  application:
    # 服务名称 - 服务之间使用名称进行通讯
    name: springcloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/heavenRoc/springcloud-config
          username: heavenRoc
          password: 6789@jkl
      label: master
    nacos:
      discovery:
        ###服务注册地址
        server-addr: 127.0.0.1:8848
